-- Run this once in Snowflake to set up the raw landing zone.
-- Adjust database/schema names to match your environment.

CREATE DATABASE IF NOT EXISTS KIKKOMAN_DB;

CREATE SCHEMA IF NOT EXISTS KIKKOMAN_DB.RAW;
CREATE SCHEMA IF NOT EXISTS KIKKOMAN_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS KIKKOMAN_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS KIKKOMAN_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS KIKKOMAN_DB.DATAMART;

CREATE TABLE IF NOT EXISTS KIKKOMAN_DB.RAW.KIKKOMAN_PRICES_RAW (
    SHOP_NAME    VARCHAR(255),
    PRODUCT_NAME VARCHAR(500),
    RAW_PRICE    VARCHAR(100),
    CURRENCY     VARCHAR(10),
    PRODUCT_URL  VARCHAR(2000),
    SCRAPED_AT   TIMESTAMP_NTZ,
    _LOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
