name: 4. dbt - Run DWH Models

on:
  workflow_dispatch:

jobs:
  dbt-dwh:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: dbt deps
        run: cd dbt && dbt deps

      - name: dbt run - dim_price and fact_price
        run: cd dbt && dbt run --select dim_price fact_price

      - name: dbt test - dwh models
        run: cd dbt && dbt test --select dim_price fact_price
