name: dbt - Run Staging Model

on:
  workflow_dispatch:

jobs:
  dbt-staging:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: dbt deps
        run: cd dbt && dbt deps

      - name: dbt run - staging_kikkoman_prices
        run: cd dbt && dbt run --select staging_kikkoman_prices

      - name: dbt test - staging_kikkoman_prices
        run: cd dbt && dbt test --select staging_kikkoman_prices
